# Generated by Django 5.1.5 on 2025-01-21 06:59

import sortedm2m.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutus_good_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='main_category',
            field=models.BooleanField(default=False, verbose_name='Основная категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='nested_categories',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='core.category', verbose_name='Дочерние категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Категория'),
        ),
    ]
