# Generated by Django 5.1.5 on 2025-02-12 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_review_options_order_order_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_datetime',
        ),
    ]
